name: onezero_flutter_lints
description: Recommended lints in Flutter projects for OneZero projects.
repository: https://github.com/onezerocompany/coding/tree/main/packages/onezero_flutter_lints
issue_tracker: https://github.com/onezerocompany/coding/issues
version: 0.0.1

environment:
  sdk: '>=2.0.0 <4.0.0'
