---
assignees:
  - lucasilverentand
live:
  enabled: true
  version:
    template: 'v{{version}}'
  requirements:
    tests: []
  release:
    manual: false
    waitForTracks: []
    platforms:
      - npm
      - docker
    allowedUsers:
      - lucasilverentand
