name: 'Setup Flutter'
description: 'Setup a Flutter environment and add it to the PATH'
author: 'OneZero Company'
inputs:
  working-directory:
    description: 'Directory to run the action in'
    required: false
    default: '.'

  version:
    description: Flutter version to use'
    required: false
    default: latest
  channel:
    description: 'Channel to read the flutter version from'
    required: false
    default: stable
  platform:
    description: 'Platform to use'
    required: false
    default: detect
  arch:
    description: 'Architecture to use'
    required: false
    default: detect

  install-dependencies:
    description: 'Whether to run flutter pub get'
    required: false
    default: 'true'

  cache:
    description: 'Whether to cache dependencies'
    required: false
    default: 'true'
  cache-key:
    description: 'Cache key for dependencies'
    required: false
    default: flutter-${{ hashFiles('**/pubspec.lock') }}-${{ hashFiles('**/Podfile') }}

  pub-credentials:
    description: 'Google account access token from ~/.pub-cache/credentials.json'
    required: false

outputs:
  version:
    description: 'The version of Flutter used'
  channel:
    description: 'The channel of Flutter used'
  platform:
    description: 'The platform of Flutter used'
  arch:
    description: 'The architecture of Flutter used'
  sdk-path:
    description: 'The path to the Flutter SDK'
  flutter-bin-path:
    description: 'The path to the Flutter binary'
  cache-hit:
    description: 'Whether the cache was hit or not'

runs:
  using: 'node16'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'

branding:
  icon: terminal
  color: 'blue'
