name: 'Publish Dart Package'
description: 'Validates commit messages'
inputs:
  pub_credentials:
    description: 'Google account access token from ~/.pub-cache/credentials.json'
    required: false
  working_directory:
    description: 'Directory to run the action in'
    required: false
    default: '.'
  version:
    description: Flutter version to use'
    required: false
    default: latest
  channel:
    description: 'Channel to read the flutter version from'
    required: false
    default: stable
  platform:
    description: 'Platform to use'
    required: false
    default: linux
  arch:
    description: 'Architecture to use'
    required: false
    default: x64
runs:
  using: 'node16'
  main: 'dist/index.js'
